# Generated by Django 4.2.11 on 2024-06-23 22:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0097_merge_20240622_1555'),
        ('review', '0026_merge_20240613_2020'),
    ]

    operations = [
        migrations.AddField(
            model_name='revisionrequest',
            name='response_letter_file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='response_letter_file', to='core.file'),
        ),
    ]
