# Generated by Django 4.2.11 on 2024-06-22 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0095_merge_20240621_0722'),
        ('core', '0096_alter_account_preferred_timezone_and_more'),
    ]

    operations = [
    ]
